api_platform:
    title: Hello API Platform
    version: 1.0.0
    formats:
        json: [ 'application/json' ]
    error_formats:
        jsonproblem: [ 'application/problem+json' ]
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
