framework:
    messenger:
        transports:
            api_to_sound_extractor:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
                serializer: App\Messenger\Serializer\ProtobufSerializer
                options:
                    exchange:
                        name: messages
                        type: direct
                    auto_setup: true
                    queues:
                        api_to_sound_extractor:
                            binding_keys: [api_to_sound_extractor]

            sound_extractor_to_api:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
                serializer: App\Messenger\Serializer\ProtobufSerializer
                options:
                    exchange:
                        name: messages
                        type: direct
                    auto_setup: true
                    queues:
                        sound_extractor_to_api:
                            binding_keys: [sound_extractor_to_api]

            api_to_subtitle_generator:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
                serializer: App\Messenger\Serializer\ProtobufSerializer
                options:
                    exchange:
                        name: messages
                        type: direct
                    auto_setup: true
                    queues:
                        api_to_subtitle_generator:
                            binding_keys: [api_to_subtitle_generator]

            subtitle_generator_to_api:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
                serializer: App\Messenger\Serializer\ProtobufSerializer
                options:
                    exchange:
                        name: messages
                        type: direct
                    auto_setup: true
                    queues:
                        subtitle_generator_to_api:
                            binding_keys: [subtitle_generator_to_api]

            api_to_subtitle_merger:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
                serializer: App\Messenger\Serializer\ProtobufSerializer
                options:
                    exchange:
                        name: messages
                        type: direct
                    auto_setup: true
                    queues:
                        api_to_subtitle_merger:
                            binding_keys: [api_to_subtitle_merger]

            subtitle_merger_to_api:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
                serializer: App\Messenger\Serializer\ProtobufSerializer
                options:
                    exchange:
                        name: messages
                        type: direct
                    auto_setup: true
                    queues:
                        subtitle_merger_to_api:
                            binding_keys: [subtitle_merger_to_api]

            api_to_subtitle_transformer:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
                serializer: App\Messenger\Serializer\ProtobufSerializer
                options:
                    exchange:
                        name: messages
                        type: direct
                    auto_setup: true
                    queues:
                        api_to_subtitle_transformer:
                            binding_keys: [api_to_subtitle_transformer]

            subtitle_transformer_to_api:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
                serializer: App\Messenger\Serializer\ProtobufSerializer
                options:
                    exchange:
                        name: messages
                        type: direct
                    auto_setup: true
                    queues:
                        subtitle_transformer_to_api:
                            binding_keys: [subtitle_transformer_to_api]

            api_to_subtitle_incrustator:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
                serializer: App\Messenger\Serializer\ProtobufSerializer
                options:
                    exchange:
                        name: messages
                        type: direct
                    auto_setup: true
                    queues:
                        api_to_subtitle_incrustator:
                            binding_keys: [api_to_subtitle_incrustator]

            subtitle_incrustator_to_api:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
                serializer: App\Messenger\Serializer\ProtobufSerializer
                options:
                    exchange:
                        name: messages
                        type: direct
                    auto_setup: true
                    queues:
                        subtitle_incrustator_to_api:
                            binding_keys: [subtitle_incrustator_to_api]

            api_to_video_formatter:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
                serializer: App\Messenger\Serializer\ProtobufSerializer
                options:
                    exchange:
                        name: messages
                        type: direct
                    auto_setup: true
                    queues:
                        api_to_video_formatter:
                            binding_keys: [api_to_video_formatter]

            video_formatter_to_api:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
                serializer: App\Messenger\Serializer\ProtobufSerializer
                options:
                    exchange:
                        name: messages
                        type: direct
                    auto_setup: true
                    queues:
                        video_formatter_to_api:
                            binding_keys: [video_formatter_to_api]

            api_to_video_splitter:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
                serializer: App\Messenger\Serializer\ProtobufSerializer
                options:
                    exchange:
                        name: messages
                        type: direct
                    auto_setup: true
                    queues:
                        api_to_video_splitter:
                            binding_keys: [api_to_video_splitter]

            video_splitter_to_api:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
                serializer: App\Messenger\Serializer\ProtobufSerializer
                options:
                    exchange:
                        name: messages
                        type: direct
                    auto_setup: true
                    queues:
                        video_splitter_to_api:
                            binding_keys: [video_splitter_to_api]

            api_to_video_incrustator:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
                serializer: App\Messenger\Serializer\ProtobufSerializer
                options:
                    exchange:
                        name: messages
                        type: direct
                    auto_setup: true
                    queues:
                        api_to_video_incrustator:
                            binding_keys: [api_to_video_incrustator]

            video_incrustator_to_api:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
                serializer: App\Messenger\Serializer\ProtobufSerializer
                options:
                    exchange:
                        name: messages
                        type: direct
                    auto_setup: true
                    queues:
                        video_incrustator_to_api:
                            binding_keys: [video_incrustator_to_api]
                            
        routing:
            'App\Protobuf\ApiToSoundExtractor': api_to_sound_extractor
            'App\Protobuf\SoundExtractorToApi': sound_extractor_to_api

            'App\Protobuf\ApiToSubtitleGenerator': api_to_subtitle_generator
            'App\Protobuf\SubtitleGeneratorToApi': subtitle_generator_to_api

            'App\Protobuf\ApiToSubtitleMerger': api_to_subtitle_merger
            'App\Protobuf\SubtitleMergerToApi': subtitle_merger_to_api

            'App\Protobuf\ApiToSubtitleTransformer': api_to_subtitle_transformer
            'App\Protobuf\SubtitleTransformerToApi': subtitle_transformer_to_api

            'App\Protobuf\ApiToSubtitleIncrustator': api_to_subtitle_incrustator
            'App\Protobuf\SubtitleIncrustatorToApi': subtitle_incrustator_to_api

            'App\Protobuf\ApiToVideoFormatter': api_to_video_formatter
            'App\Protobuf\VideoFormatterToApi': video_formatter_to_api

            'App\Protobuf\ApiToVideoSplitter': api_to_video_splitter
            'App\Protobuf\VideoSplitterToApi': video_splitter_to_api

            'App\Protobuf\ApiToVideoIncrustator': api_to_video_incrustator
            'App\Protobuf\VideoIncrustatorToApi': video_incrustator_to_api
