services:
    php:
        container_name: ${PROJECT_NAME}-php
        image: ${IMAGES_PREFIX:-}app-php
        restart: unless-stopped
        networks:
            - api_network
        depends_on:
            - database
            - rabbitmq
        environment:
            SERVER_NAME: ${SERVER_NAME:-localhost}, php:80
            MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
            MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
            MERCURE_URL: ${CADDY_MERCURE_URL:-http://php/.well-known/mercure}
            MERCURE_PUBLIC_URL: ${CADDY_MERCURE_PUBLIC_URL:-https://${SERVER_NAME:-localhost}/.well-known/mercure}
            MERCURE_JWT_SECRET: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
        volumes:
            - caddy_data:/data
            - caddy_config:/config
        ports:
            - target: 80
              published: ${HTTP_PORT:-80}
              protocol: tcp
            - target: 443
              published: ${HTTPS_PORT:-443}
              protocol: tcp
            - target: 443
              published: ${HTTP3_PORT:-443}
              protocol: udp
            
    database:
        image: postgres:latest
        container_name: ${PROJECT_NAME}-db
        env_file:
            - .env.local
        networks:
            - api_network
        volumes:
            - database_data:/var/lib/postgresql/data
        ports:
            - "9001:5432"
        restart: unless-stopped

    rabbitmq:
        container_name: ${PROJECT_NAME}-rabbitmq
        restart: unless-stopped
        image: rabbitmq:3-management
        hostname: rabbitmq
        networks:
            - api_network
        environment:
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
            RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VHOST}
            RABBITMQ_USER: ${RABBITMQ_USER}
            RABBITMQ_PASS: ${RABBITMQ_PASS}
            RABBITMQ_VHOST: ${RABBITMQ_VHOST}
        volumes:
            - rabbitmq_data:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit
        ports:
            - "9002:5672"
            - "9003:15672"
    
    minio:
        container_name: ${PROJECT_NAME}-s3
        image: minio/minio:latest
        env_file:
            - .env.local
        ports:
            - '9004:9000'
            - '9005:9001'
        networks:
            - api_network
        volumes:
            - minio_data:/data/minio
        command: 'minio server /data/minio --console-address ":9001"'
        environment:
            MINIO_DEFAULT_BUCKETS: ${S3_DEFAULT_BUCKETS}

    qa:
        container_name: ${PROJECT_NAME}-qa
        image: php:8.3-cli-alpine
        volumes:
            - ./src:/app/src
        working_dir: /app
        tty: true
        command: >
            sh -c "apk add --no-cache wget composer &&
            wget https://cs.symfony.com/download/php-cs-fixer-v3.phar -O php-cs-fixer &&
            chmod a+x php-cs-fixer &&
            composer require --dev phpstan/phpstan &&
            tail -f /dev/null"

networks:
  api_network:
    name: api_network
    driver: bridge

volumes:
    caddy_data:
    caddy_config:
    database_data:
    rabbitmq_data:
    minio_data:
