<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Message.proto

namespace App\Protobuf\GPBMetadata;

class Message
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
û
Message.protoApp.Protobuf"?
ApiToSoundExtractor(
mediaPod (2.App.Protobuf.MediaPod"?
SoundExtractorToApi(
mediaPod (2.App.Protobuf.MediaPod"B
ApiToSubtitleGenerator(
mediaPod (2.App.Protobuf.MediaPod"B
SubtitleGeneratorToApi(
mediaPod (2.App.Protobuf.MediaPod"?
ApiToSubtitleMerger(
mediaPod (2.App.Protobuf.MediaPod"?
SubtitleMergerToApi(
mediaPod (2.App.Protobuf.MediaPod"D
ApiToSubtitleIncrustator(
mediaPod (2.App.Protobuf.MediaPod"D
SubtitleIncrustatorToApi(
mediaPod (2.App.Protobuf.MediaPod"Š
MediaPod
uuid (	
userUuid (	*
originalVideo (2.App.Protobuf.Video"
video (2.App.Protobuf.Video
status (	" 
Video
name (	
mimeType (	
size (
length (
subtitle (	
	subtitles (	
audios (	$
preset (2.App.Protobuf.Preset"`
Preset
subtitleFont (	
subtitleSize (	
subtitleColor (	
videoFormat (	B*ÊApp\\ProtobufâApp\\Protobuf\\GPBMetadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

