<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Message.proto

namespace App\Protobuf\GPBMetadata;

class Message
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
ë
Message.protoApp.Protobuf"=
ApiSoundExtractor(
mediaPod (2.App.Protobuf.MediaPod"=
SoundExtractorApi(
mediaPod (2.App.Protobuf.MediaPod"@
ApiSubtitleGenerator(
mediaPod (2.App.Protobuf.MediaPod"@
SubtitleGeneratorApi(
mediaPod (2.App.Protobuf.MediaPod"=
ApiSubtitleMerger(
mediaPod (2.App.Protobuf.MediaPod"=
SubtitleMergerApi(
mediaPod (2.App.Protobuf.MediaPod"B
ApiSubtitleIncrustator(
mediaPod (2.App.Protobuf.MediaPod"B
SubtitleIncrustatorApi(
mediaPod (2.App.Protobuf.MediaPod"Š
MediaPod
uuid (	
userUuid (	*
originalVideo (2.App.Protobuf.Video"
video (2.App.Protobuf.Video
status (	" 
Video
name (	
mimeType (	
size (
length (
subtitle (	
	subtitles (	
audios (	$
preset (2.App.Protobuf.Preset"`
Preset
subtitleFont (	
subtitleSize (	
subtitleColor (	
videoFormat (	B*ÊApp\\ProtobufâApp\\Protobuf\\GPBMetadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

