<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

namespace App\Protobuf;

/**
 * Protobuf type <code>App.Protobuf.ConfigurationSubtitleShadow</code>.
 */
class ConfigurationSubtitleShadow
{
    /**
     * Generated from protobuf enum <code>SHADOW_NONE = 0;</code>.
     */
    public const SHADOW_NONE = 0;
    /**
     * Generated from protobuf enum <code>SHADOW_SOFT = 1;</code>.
     */
    public const SHADOW_SOFT = 1;
    /**
     * Generated from protobuf enum <code>SHADOW_MEDIUM = 2;</code>.
     */
    public const SHADOW_MEDIUM = 2;
    /**
     * Generated from protobuf enum <code>SHADOW_HARD = 4;</code>.
     */
    public const SHADOW_HARD = 4;

    private static $valueToName = [
        self::SHADOW_NONE => 'SHADOW_NONE',
        self::SHADOW_SOFT => 'SHADOW_SOFT',
        self::SHADOW_MEDIUM => 'SHADOW_MEDIUM',
        self::SHADOW_HARD => 'SHADOW_HARD',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new \UnexpectedValueException(sprintf('Enum %s has no name defined for value %s', __CLASS__, $value));
        }

        return self::$valueToName[$value];
    }

    public static function value($name)
    {
        $const = __CLASS__.'::'.strtoupper($name);
        if (!defined($const)) {
            throw new \UnexpectedValueException(sprintf('Enum %s has no value defined for name %s', __CLASS__, $name));
        }

        return constant($const);
    }
}
