<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Message.proto

namespace App\Protobuf;

use UnexpectedValueException;

/**
 * Protobuf type <code>App.Protobuf.ConfigurationSubtitleFont</code>
 */
class ConfigurationSubtitleFont
{
    /**
     * Generated from protobuf enum <code>ARIAL = 0;</code>
     */
    const ARIAL = 0;
    /**
     * Generated from protobuf enum <code>TIMES_NEW_ROMAN = 1;</code>
     */
    const TIMES_NEW_ROMAN = 1;
    /**
     * Generated from protobuf enum <code>COURIER_NEW = 2;</code>
     */
    const COURIER_NEW = 2;

    private static $valueToName = [
        self::ARIAL => 'ARIAL',
        self::TIMES_NEW_ROMAN => 'TIMES_NEW_ROMAN',
        self::COURIER_NEW => 'COURIER_NEW',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

