<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

namespace App\Protobuf;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>App.Protobuf.Configuration</code>.
 */
class Configuration extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string subtitleFont = 1;</code>.
     */
    protected $subtitleFont = '';
    /**
     * Generated from protobuf field <code>string subtitleSize = 2;</code>.
     */
    protected $subtitleSize = '';
    /**
     * Generated from protobuf field <code>string subtitleColor = 3;</code>.
     */
    protected $subtitleColor = '';
    /**
     * Generated from protobuf field <code>string subtitleBold = 4;</code>.
     */
    protected $subtitleBold = '';
    /**
     * Generated from protobuf field <code>string subtitleItalic = 5;</code>.
     */
    protected $subtitleItalic = '';
    /**
     * Generated from protobuf field <code>string subtitleUnderline = 6;</code>.
     */
    protected $subtitleUnderline = '';
    /**
     * Generated from protobuf field <code>string subtitleOutlineColor = 7;</code>.
     */
    protected $subtitleOutlineColor = '';
    /**
     * Generated from protobuf field <code>string subtitleOutlineThickness = 8;</code>.
     */
    protected $subtitleOutlineThickness = '';
    /**
     * Generated from protobuf field <code>string subtitleShadow = 9;</code>.
     */
    protected $subtitleShadow = '';
    /**
     * Generated from protobuf field <code>string subtitleShadowColor = 10;</code>.
     */
    protected $subtitleShadowColor = '';
    /**
     * Generated from protobuf field <code>string format = 11;</code>.
     */
    protected $format = '';
    /**
     * Generated from protobuf field <code>string split = 12;</code>.
     */
    protected $split = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *                    Optional. Data for populating the Message object.
     *
     * @var string $subtitleFont
     * @var string $subtitleSize
     * @var string $subtitleColor
     * @var string $subtitleBold
     * @var string $subtitleItalic
     * @var string $subtitleUnderline
     * @var string $subtitleOutlineColor
     * @var string $subtitleOutlineThickness
     * @var string $subtitleShadow
     * @var string $subtitleShadowColor
     * @var string $format
     * @var string $split
     *             }
     */
    public function __construct($data = null)
    {
        GPBMetadata\Message::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string subtitleFont = 1;</code>.
     *
     * @return string
     */
    public function getSubtitleFont()
    {
        return $this->subtitleFont;
    }

    /**
     * Generated from protobuf field <code>string subtitleFont = 1;</code>.
     *
     * @param string $var
     *
     * @return $this
     */
    public function setSubtitleFont($var)
    {
        GPBUtil::checkString($var, true);
        $this->subtitleFont = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string subtitleSize = 2;</code>.
     *
     * @return string
     */
    public function getSubtitleSize()
    {
        return $this->subtitleSize;
    }

    /**
     * Generated from protobuf field <code>string subtitleSize = 2;</code>.
     *
     * @param string $var
     *
     * @return $this
     */
    public function setSubtitleSize($var)
    {
        GPBUtil::checkString($var, true);
        $this->subtitleSize = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string subtitleColor = 3;</code>.
     *
     * @return string
     */
    public function getSubtitleColor()
    {
        return $this->subtitleColor;
    }

    /**
     * Generated from protobuf field <code>string subtitleColor = 3;</code>.
     *
     * @param string $var
     *
     * @return $this
     */
    public function setSubtitleColor($var)
    {
        GPBUtil::checkString($var, true);
        $this->subtitleColor = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string subtitleBold = 4;</code>.
     *
     * @return string
     */
    public function getSubtitleBold()
    {
        return $this->subtitleBold;
    }

    /**
     * Generated from protobuf field <code>string subtitleBold = 4;</code>.
     *
     * @param string $var
     *
     * @return $this
     */
    public function setSubtitleBold($var)
    {
        GPBUtil::checkString($var, true);
        $this->subtitleBold = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string subtitleItalic = 5;</code>.
     *
     * @return string
     */
    public function getSubtitleItalic()
    {
        return $this->subtitleItalic;
    }

    /**
     * Generated from protobuf field <code>string subtitleItalic = 5;</code>.
     *
     * @param string $var
     *
     * @return $this
     */
    public function setSubtitleItalic($var)
    {
        GPBUtil::checkString($var, true);
        $this->subtitleItalic = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string subtitleUnderline = 6;</code>.
     *
     * @return string
     */
    public function getSubtitleUnderline()
    {
        return $this->subtitleUnderline;
    }

    /**
     * Generated from protobuf field <code>string subtitleUnderline = 6;</code>.
     *
     * @param string $var
     *
     * @return $this
     */
    public function setSubtitleUnderline($var)
    {
        GPBUtil::checkString($var, true);
        $this->subtitleUnderline = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string subtitleOutlineColor = 7;</code>.
     *
     * @return string
     */
    public function getSubtitleOutlineColor()
    {
        return $this->subtitleOutlineColor;
    }

    /**
     * Generated from protobuf field <code>string subtitleOutlineColor = 7;</code>.
     *
     * @param string $var
     *
     * @return $this
     */
    public function setSubtitleOutlineColor($var)
    {
        GPBUtil::checkString($var, true);
        $this->subtitleOutlineColor = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string subtitleOutlineThickness = 8;</code>.
     *
     * @return string
     */
    public function getSubtitleOutlineThickness()
    {
        return $this->subtitleOutlineThickness;
    }

    /**
     * Generated from protobuf field <code>string subtitleOutlineThickness = 8;</code>.
     *
     * @param string $var
     *
     * @return $this
     */
    public function setSubtitleOutlineThickness($var)
    {
        GPBUtil::checkString($var, true);
        $this->subtitleOutlineThickness = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string subtitleShadow = 9;</code>.
     *
     * @return string
     */
    public function getSubtitleShadow()
    {
        return $this->subtitleShadow;
    }

    /**
     * Generated from protobuf field <code>string subtitleShadow = 9;</code>.
     *
     * @param string $var
     *
     * @return $this
     */
    public function setSubtitleShadow($var)
    {
        GPBUtil::checkString($var, true);
        $this->subtitleShadow = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string subtitleShadowColor = 10;</code>.
     *
     * @return string
     */
    public function getSubtitleShadowColor()
    {
        return $this->subtitleShadowColor;
    }

    /**
     * Generated from protobuf field <code>string subtitleShadowColor = 10;</code>.
     *
     * @param string $var
     *
     * @return $this
     */
    public function setSubtitleShadowColor($var)
    {
        GPBUtil::checkString($var, true);
        $this->subtitleShadowColor = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string format = 11;</code>.
     *
     * @return string
     */
    public function getFormat()
    {
        return $this->format;
    }

    /**
     * Generated from protobuf field <code>string format = 11;</code>.
     *
     * @param string $var
     *
     * @return $this
     */
    public function setFormat($var)
    {
        GPBUtil::checkString($var, true);
        $this->format = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string split = 12;</code>.
     *
     * @return string
     */
    public function getSplit()
    {
        return $this->split;
    }

    /**
     * Generated from protobuf field <code>string split = 12;</code>.
     *
     * @param string $var
     *
     * @return $this
     */
    public function setSplit($var)
    {
        GPBUtil::checkString($var, true);
        $this->split = $var;

        return $this;
    }
}
