<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Message.proto

namespace App\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>App.Protobuf.Format</code>
 */
class Format extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string style = 1;</code>
     */
    protected $style = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $style
     * }
     */
    public function __construct($data = NULL) {
        \App\Protobuf\GPBMetadata\Message::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string style = 1;</code>
     * @return string
     */
    public function getStyle()
    {
        return $this->style;
    }

    /**
     * Generated from protobuf field <code>string style = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setStyle($var)
    {
        GPBUtil::checkString($var, True);
        $this->style = $var;

        return $this;
    }

}

