<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Message.proto

namespace App\Protobuf;

use UnexpectedValueException;

/**
 * Protobuf type <code>App.Protobuf.MediaPodStatus</code>
 */
class MediaPodStatus
{
    /**
     * Generated from protobuf enum <code>UPLOAD_COMPLETE = 0;</code>
     */
    const UPLOAD_COMPLETE = 0;
    /**
     * Generated from protobuf enum <code>SOUND_EXTRACTOR_PENDING = 1;</code>
     */
    const SOUND_EXTRACTOR_PENDING = 1;
    /**
     * Generated from protobuf enum <code>SOUND_EXTRACTOR_COMPLETE = 2;</code>
     */
    const SOUND_EXTRACTOR_COMPLETE = 2;
    /**
     * Generated from protobuf enum <code>SOUND_EXTRACTOR_ERROR = 3;</code>
     */
    const SOUND_EXTRACTOR_ERROR = 3;
    /**
     * Generated from protobuf enum <code>SUBTITLE_GENERATOR_PENDING = 4;</code>
     */
    const SUBTITLE_GENERATOR_PENDING = 4;
    /**
     * Generated from protobuf enum <code>SUBTITLE_GENERATOR_COMPLETE = 5;</code>
     */
    const SUBTITLE_GENERATOR_COMPLETE = 5;
    /**
     * Generated from protobuf enum <code>SUBTITLE_GENERATOR_ERROR = 6;</code>
     */
    const SUBTITLE_GENERATOR_ERROR = 6;
    /**
     * Generated from protobuf enum <code>SUBTITLE_MERGER_PENDING = 7;</code>
     */
    const SUBTITLE_MERGER_PENDING = 7;
    /**
     * Generated from protobuf enum <code>SUBTITLE_MERGER_COMPLETE = 8;</code>
     */
    const SUBTITLE_MERGER_COMPLETE = 8;
    /**
     * Generated from protobuf enum <code>SUBTITLE_MERGER_ERROR = 9;</code>
     */
    const SUBTITLE_MERGER_ERROR = 9;
    /**
     * Generated from protobuf enum <code>SUBTITLE_TRANSFORMER_PENDING = 10;</code>
     */
    const SUBTITLE_TRANSFORMER_PENDING = 10;
    /**
     * Generated from protobuf enum <code>SUBTITLE_TRANSFORMER_COMPLETE = 11;</code>
     */
    const SUBTITLE_TRANSFORMER_COMPLETE = 11;
    /**
     * Generated from protobuf enum <code>SUBTITLE_TRANSFORMER_ERROR = 12;</code>
     */
    const SUBTITLE_TRANSFORMER_ERROR = 12;
    /**
     * Generated from protobuf enum <code>SUBTITLE_INCRUSTATOR_PENDING = 13;</code>
     */
    const SUBTITLE_INCRUSTATOR_PENDING = 13;
    /**
     * Generated from protobuf enum <code>SUBTITLE_INCRUSTATOR_COMPLETE = 14;</code>
     */
    const SUBTITLE_INCRUSTATOR_COMPLETE = 14;
    /**
     * Generated from protobuf enum <code>SUBTITLE_INCRUSTATOR_ERROR = 15;</code>
     */
    const SUBTITLE_INCRUSTATOR_ERROR = 15;
    /**
     * Generated from protobuf enum <code>SUBTITLE_FORMATTER_PENDING = 16;</code>
     */
    const SUBTITLE_FORMATTER_PENDING = 16;
    /**
     * Generated from protobuf enum <code>SUBTITLE_FORMATTER_COMPLETE = 17;</code>
     */
    const SUBTITLE_FORMATTER_COMPLETE = 17;
    /**
     * Generated from protobuf enum <code>SUBTITLE_FORMATTER_ERROR = 18;</code>
     */
    const SUBTITLE_FORMATTER_ERROR = 18;
    /**
     * Generated from protobuf enum <code>RESIZING = 19;</code>
     */
    const RESIZING = 19;
    /**
     * Generated from protobuf enum <code>RESIZED = 20;</code>
     */
    const RESIZED = 20;
    /**
     * Generated from protobuf enum <code>READY_FOR_EXPORT = 21;</code>
     */
    const READY_FOR_EXPORT = 21;
    /**
     * Generated from protobuf enum <code>ERROR = 22;</code>
     */
    const ERROR = 22;

    private static $valueToName = [
        self::UPLOAD_COMPLETE => 'UPLOAD_COMPLETE',
        self::SOUND_EXTRACTOR_PENDING => 'SOUND_EXTRACTOR_PENDING',
        self::SOUND_EXTRACTOR_COMPLETE => 'SOUND_EXTRACTOR_COMPLETE',
        self::SOUND_EXTRACTOR_ERROR => 'SOUND_EXTRACTOR_ERROR',
        self::SUBTITLE_GENERATOR_PENDING => 'SUBTITLE_GENERATOR_PENDING',
        self::SUBTITLE_GENERATOR_COMPLETE => 'SUBTITLE_GENERATOR_COMPLETE',
        self::SUBTITLE_GENERATOR_ERROR => 'SUBTITLE_GENERATOR_ERROR',
        self::SUBTITLE_MERGER_PENDING => 'SUBTITLE_MERGER_PENDING',
        self::SUBTITLE_MERGER_COMPLETE => 'SUBTITLE_MERGER_COMPLETE',
        self::SUBTITLE_MERGER_ERROR => 'SUBTITLE_MERGER_ERROR',
        self::SUBTITLE_TRANSFORMER_PENDING => 'SUBTITLE_TRANSFORMER_PENDING',
        self::SUBTITLE_TRANSFORMER_COMPLETE => 'SUBTITLE_TRANSFORMER_COMPLETE',
        self::SUBTITLE_TRANSFORMER_ERROR => 'SUBTITLE_TRANSFORMER_ERROR',
        self::SUBTITLE_INCRUSTATOR_PENDING => 'SUBTITLE_INCRUSTATOR_PENDING',
        self::SUBTITLE_INCRUSTATOR_COMPLETE => 'SUBTITLE_INCRUSTATOR_COMPLETE',
        self::SUBTITLE_INCRUSTATOR_ERROR => 'SUBTITLE_INCRUSTATOR_ERROR',
        self::SUBTITLE_FORMATTER_PENDING => 'SUBTITLE_FORMATTER_PENDING',
        self::SUBTITLE_FORMATTER_COMPLETE => 'SUBTITLE_FORMATTER_COMPLETE',
        self::SUBTITLE_FORMATTER_ERROR => 'SUBTITLE_FORMATTER_ERROR',
        self::RESIZING => 'RESIZING',
        self::RESIZED => 'RESIZED',
        self::READY_FOR_EXPORT => 'READY_FOR_EXPORT',
        self::ERROR => 'ERROR',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

