<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Message.proto

namespace App\Protobuf;

use UnexpectedValueException;

/**
 * Protobuf type <code>App.Protobuf.PresetSubtitleOutlineThickness</code>
 */
class PresetSubtitleOutlineThickness
{
    /**
     * Generated from protobuf enum <code>OUTLINE_NONE = 0;</code>
     */
    const OUTLINE_NONE = 0;
    /**
     * Generated from protobuf enum <code>OUTLINE_SOFT = 1;</code>
     */
    const OUTLINE_SOFT = 1;
    /**
     * Generated from protobuf enum <code>OUTLINE_MEDIUM = 2;</code>
     */
    const OUTLINE_MEDIUM = 2;
    /**
     * Generated from protobuf enum <code>OUTLINE_HARD = 4;</code>
     */
    const OUTLINE_HARD = 4;

    private static $valueToName = [
        self::OUTLINE_NONE => 'OUTLINE_NONE',
        self::OUTLINE_SOFT => 'OUTLINE_SOFT',
        self::OUTLINE_MEDIUM => 'OUTLINE_MEDIUM',
        self::OUTLINE_HARD => 'OUTLINE_HARD',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

