<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

namespace App\Protobuf;

/**
 * Protobuf type <code>App.Protobuf.PresetSubtitleShadow</code>.
 */
class PresetSubtitleShadow
{
    /**
     * Generated from protobuf enum <code>NONE = 0;</code>.
     */
    public const NONE = 0;
    /**
     * Generated from protobuf enum <code>SOFT = 1;</code>.
     */
    public const SOFT = 1;
    /**
     * Generated from protobuf enum <code>HARD = 2;</code>.
     */
    public const HARD = 2;

    private static $valueToName = [
        self::NONE => 'NONE',
        self::SOFT => 'SOFT',
        self::HARD => 'HARD',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new \UnexpectedValueException(sprintf('Enum %s has no name defined for value %s', __CLASS__, $value));
        }

        return self::$valueToName[$value];
    }

    public static function value($name)
    {
        $const = __CLASS__.'::'.strtoupper($name);
        if (!defined($const)) {
            throw new \UnexpectedValueException(sprintf('Enum %s has no value defined for name %s', __CLASS__, $name));
        }

        return constant($const);
    }
}
