<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

namespace App\Protobuf;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>App.Protobuf.Preset</code>.
 */
class Preset extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string subtitleFont = 1;</code>.
     */
    protected $subtitleFont = '';
    /**
     * Generated from protobuf field <code>string subtitleSize = 2;</code>.
     */
    protected $subtitleSize = '';
    /**
     * Generated from protobuf field <code>string subtitleColor = 3;</code>.
     */
    protected $subtitleColor = '';
    /**
     * Generated from protobuf field <code>string subtitleBackground = 4;</code>.
     */
    protected $subtitleBackground = '';
    /**
     * Generated from protobuf field <code>string subtitleOutlineColor = 5;</code>.
     */
    protected $subtitleOutlineColor = '';
    /**
     * Generated from protobuf field <code>string subtitleOutlineThickness = 6;</code>.
     */
    protected $subtitleOutlineThickness = '';
    /**
     * Generated from protobuf field <code>string subtitleShadow = 7;</code>.
     */
    protected $subtitleShadow = '';
    /**
     * Generated from protobuf field <code>string subtitleShadowColor = 8;</code>.
     */
    protected $subtitleShadowColor = '';
    /**
     * Generated from protobuf field <code>string videoResolution = 9;</code>.
     */
    protected $videoResolution = '';
    /**
     * Generated from protobuf field <code>string videoAspectRatio = 10;</code>.
     */
    protected $videoAspectRatio = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *                    Optional. Data for populating the Message object.
     *
     * @var string $subtitleFont
     * @var string $subtitleSize
     * @var string $subtitleColor
     * @var string $subtitleBackground
     * @var string $subtitleOutlineColor
     * @var string $subtitleOutlineThickness
     * @var string $subtitleShadow
     * @var string $subtitleShadowColor
     * @var string $videoResolution
     * @var string $videoAspectRatio
     *             }
     */
    public function __construct($data = null)
    {
        GPBMetadata\Message::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string subtitleFont = 1;</code>.
     *
     * @return string
     */
    public function getSubtitleFont()
    {
        return $this->subtitleFont;
    }

    /**
     * Generated from protobuf field <code>string subtitleFont = 1;</code>.
     *
     * @param string $var
     *
     * @return $this
     */
    public function setSubtitleFont($var)
    {
        GPBUtil::checkString($var, true);
        $this->subtitleFont = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string subtitleSize = 2;</code>.
     *
     * @return string
     */
    public function getSubtitleSize()
    {
        return $this->subtitleSize;
    }

    /**
     * Generated from protobuf field <code>string subtitleSize = 2;</code>.
     *
     * @param string $var
     *
     * @return $this
     */
    public function setSubtitleSize($var)
    {
        GPBUtil::checkString($var, true);
        $this->subtitleSize = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string subtitleColor = 3;</code>.
     *
     * @return string
     */
    public function getSubtitleColor()
    {
        return $this->subtitleColor;
    }

    /**
     * Generated from protobuf field <code>string subtitleColor = 3;</code>.
     *
     * @param string $var
     *
     * @return $this
     */
    public function setSubtitleColor($var)
    {
        GPBUtil::checkString($var, true);
        $this->subtitleColor = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string subtitleBackground = 4;</code>.
     *
     * @return string
     */
    public function getSubtitleBackground()
    {
        return $this->subtitleBackground;
    }

    /**
     * Generated from protobuf field <code>string subtitleBackground = 4;</code>.
     *
     * @param string $var
     *
     * @return $this
     */
    public function setSubtitleBackground($var)
    {
        GPBUtil::checkString($var, true);
        $this->subtitleBackground = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string subtitleOutlineColor = 5;</code>.
     *
     * @return string
     */
    public function getSubtitleOutlineColor()
    {
        return $this->subtitleOutlineColor;
    }

    /**
     * Generated from protobuf field <code>string subtitleOutlineColor = 5;</code>.
     *
     * @param string $var
     *
     * @return $this
     */
    public function setSubtitleOutlineColor($var)
    {
        GPBUtil::checkString($var, true);
        $this->subtitleOutlineColor = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string subtitleOutlineThickness = 6;</code>.
     *
     * @return string
     */
    public function getSubtitleOutlineThickness()
    {
        return $this->subtitleOutlineThickness;
    }

    /**
     * Generated from protobuf field <code>string subtitleOutlineThickness = 6;</code>.
     *
     * @param string $var
     *
     * @return $this
     */
    public function setSubtitleOutlineThickness($var)
    {
        GPBUtil::checkString($var, true);
        $this->subtitleOutlineThickness = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string subtitleShadow = 7;</code>.
     *
     * @return string
     */
    public function getSubtitleShadow()
    {
        return $this->subtitleShadow;
    }

    /**
     * Generated from protobuf field <code>string subtitleShadow = 7;</code>.
     *
     * @param string $var
     *
     * @return $this
     */
    public function setSubtitleShadow($var)
    {
        GPBUtil::checkString($var, true);
        $this->subtitleShadow = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string subtitleShadowColor = 8;</code>.
     *
     * @return string
     */
    public function getSubtitleShadowColor()
    {
        return $this->subtitleShadowColor;
    }

    /**
     * Generated from protobuf field <code>string subtitleShadowColor = 8;</code>.
     *
     * @param string $var
     *
     * @return $this
     */
    public function setSubtitleShadowColor($var)
    {
        GPBUtil::checkString($var, true);
        $this->subtitleShadowColor = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string videoResolution = 9;</code>.
     *
     * @return string
     */
    public function getVideoResolution()
    {
        return $this->videoResolution;
    }

    /**
     * Generated from protobuf field <code>string videoResolution = 9;</code>.
     *
     * @param string $var
     *
     * @return $this
     */
    public function setVideoResolution($var)
    {
        GPBUtil::checkString($var, true);
        $this->videoResolution = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string videoAspectRatio = 10;</code>.
     *
     * @return string
     */
    public function getVideoAspectRatio()
    {
        return $this->videoAspectRatio;
    }

    /**
     * Generated from protobuf field <code>string videoAspectRatio = 10;</code>.
     *
     * @param string $var
     *
     * @return $this
     */
    public function setVideoAspectRatio($var)
    {
        GPBUtil::checkString($var, true);
        $this->videoAspectRatio = $var;

        return $this;
    }
}
