<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

namespace App\Protobuf;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>App.Protobuf.Preset</code>.
 */
class Preset extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string subtitleFont = 1;</code>.
     */
    protected $subtitleFont = '';
    /**
     * Generated from protobuf field <code>string subtitleSize = 2;</code>.
     */
    protected $subtitleSize = '';
    /**
     * Generated from protobuf field <code>string subtitleColor = 3;</code>.
     */
    protected $subtitleColor = '';
    /**
     * Generated from protobuf field <code>string videoFormat = 4;</code>.
     */
    protected $videoFormat = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *                    Optional. Data for populating the Message object.
     *
     * @var string $subtitleFont
     * @var string $subtitleSize
     * @var string $subtitleColor
     * @var string $videoFormat
     *             }
     */
    public function __construct($data = null)
    {
        GPBMetadata\Message::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string subtitleFont = 1;</code>.
     *
     * @return string
     */
    public function getSubtitleFont()
    {
        return $this->subtitleFont;
    }

    /**
     * Generated from protobuf field <code>string subtitleFont = 1;</code>.
     *
     * @param string $var
     *
     * @return $this
     */
    public function setSubtitleFont($var)
    {
        GPBUtil::checkString($var, true);
        $this->subtitleFont = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string subtitleSize = 2;</code>.
     *
     * @return string
     */
    public function getSubtitleSize()
    {
        return $this->subtitleSize;
    }

    /**
     * Generated from protobuf field <code>string subtitleSize = 2;</code>.
     *
     * @param string $var
     *
     * @return $this
     */
    public function setSubtitleSize($var)
    {
        GPBUtil::checkString($var, true);
        $this->subtitleSize = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string subtitleColor = 3;</code>.
     *
     * @return string
     */
    public function getSubtitleColor()
    {
        return $this->subtitleColor;
    }

    /**
     * Generated from protobuf field <code>string subtitleColor = 3;</code>.
     *
     * @param string $var
     *
     * @return $this
     */
    public function setSubtitleColor($var)
    {
        GPBUtil::checkString($var, true);
        $this->subtitleColor = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string videoFormat = 4;</code>.
     *
     * @return string
     */
    public function getVideoFormat()
    {
        return $this->videoFormat;
    }

    /**
     * Generated from protobuf field <code>string videoFormat = 4;</code>.
     *
     * @param string $var
     *
     * @return $this
     */
    public function setVideoFormat($var)
    {
        GPBUtil::checkString($var, true);
        $this->videoFormat = $var;

        return $this;
    }
}
