<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

namespace App\Protobuf;

/**
 * Protobuf type <code>App.Protobuf.VideoFormatStyle</code>.
 */
class VideoFormatStyle
{
    /**
     * Generated from protobuf enum <code>ORIGINAL = 0;</code>.
     */
    public const ORIGINAL = 0;
    /**
     * Generated from protobuf enum <code>ZOOMED_916 = 1;</code>.
     */
    public const ZOOMED_916 = 1;
    /**
     * Generated from protobuf enum <code>NORMAL_916_WITH_BORDERS = 2;</code>.
     */
    public const NORMAL_916_WITH_BORDERS = 2;
    /**
     * Generated from protobuf enum <code>DUPLICATED_BLURRED_916 = 3;</code>.
     */
    public const DUPLICATED_BLURRED_916 = 3;

    private static $valueToName = [
        self::ORIGINAL => 'ORIGINAL',
        self::ZOOMED_916 => 'ZOOMED_916',
        self::NORMAL_916_WITH_BORDERS => 'NORMAL_916_WITH_BORDERS',
        self::DUPLICATED_BLURRED_916 => 'DUPLICATED_BLURRED_916',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new \UnexpectedValueException(sprintf('Enum %s has no name defined for value %s', __CLASS__, $value));
        }

        return self::$valueToName[$value];
    }

    public static function value($name)
    {
        $const = __CLASS__.'::'.strtoupper($name);
        if (!defined($const)) {
            throw new \UnexpectedValueException(sprintf('Enum %s has no value defined for name %s', __CLASS__, $name));
        }

        return constant($const);
    }
}
