parameters:
    transport_dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
    secret_webhook_user: '%env(SECRET_WEBHOOK_USER)%'
    secret_webhook_user_deleted: '%env(SECRET_WEBHOOK_USER_DELETED)%'
    clerk_publishable_key: '%env(CLERK_PUBLISHABLE_KEY)%'
    master_key: '%env(MASTER_KEY)%'
    front_url: '%env(FRONT_URL)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            string $transportDsn: '%transport_dsn%'
            string $secretWebhookUser: '%secret_webhook_user%'
            string $secretWebhookUserDeleted: '%secret_webhook_user_deleted%'
            string $clerkPublishableKey: '%clerk_publishable_key%'
            string $masterKey: '%master_key%'
            string $frontUrl: '%front_url%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    Aws\S3\S3Client:
        arguments:
            -   version: 'latest'
                region: '%env(S3_REGION)%'
                endpoint: '%env(S3_ENDPOINT)%'
                use_path_style_endpoint: true
                credentials:
                    key: '%env(S3_ACCESS_KEY)%'
                    secret: '%env(S3_SECRET_KEY)%'
                    
    App\EventListener\JwtResponseListener:
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_success, method: onAuthenticationSuccessResponse }
